import type { Deal } from "./types";

export const demoDeals: Deal[] = [
  {
    id: "demo-nike",
    user_id: null,
    created_at: "2026-08-28T08:00:00Z",
    updated_at: "2026-08-28T08:00:00Z",
    brand: "Nike",
    product_name: "黑色运动裤",
    product_category: "裤子",
    cooperation_date: "2026-08-24",
    product_image_url: null,
    platform: "小红书",
    platforms: ["小红书"],
    product_price: 399,
    base_fee: 800,
    commission: "10%",
    advance_amount: 399,
    received_date: "2026-08-26",
    shoot_deadline: "2026-08-31",
    shoot_date: "2026-08-29",
    publish_deadline: "2026-09-03",
    publish_date: null,
    expected_payment_date: "2026-09-18",
    payment_received: false,
    payment_received_date: null,
    expected_refund_date: "2026-09-18",
    refund_received: false,
    refund_received_date: null,
    product_url: "",
    publish_url: "",
    notes: "健身房或户外场景，评论区带品牌 tag。",
    completed: false,
    archived_at: null,
  },
  {
    id: "demo-ubras",
    user_id: null,
    created_at: "2026-08-27T08:00:00Z",
    updated_at: "2026-08-27T08:00:00Z",
    brand: "Ubras",
    product_name: "白色上衣",
    product_category: "上衣",
    cooperation_date: "2026-08-27",
    product_image_url: null,
    platform: "抖音",
    platforms: ["抖音"],
    product_price: null,
    base_fee: 600,
    commission: "",
    advance_amount: null,
    received_date: null,
    shoot_deadline: "2026-09-01",
    shoot_date: null,
    publish_deadline: "2026-09-05",
    publish_date: null,
    expected_payment_date: null,
    payment_received: false,
    payment_received_date: null,
    expected_refund_date: null,
    refund_received: false,
    refund_received_date: null,
    product_url: "",
    publish_url: "",
    notes: "",
    completed: false,
    archived_at: null,
  },
  {
    id: "demo-adidas",
    user_id: null,
    created_at: "2026-08-26T08:00:00Z",
    updated_at: "2026-08-26T08:00:00Z",
    brand: "Adidas",
    product_name: "白鞋",
    product_category: "鞋子",
    cooperation_date: "2026-08-26",
    product_image_url: null,
    platform: "小红书",
    platforms: ["小红书"],
    product_price: 399,
    base_fee: null,
    commission: "",
    advance_amount: 399,
    received_date: null,
    shoot_deadline: null,
    shoot_date: null,
    publish_deadline: null,
    publish_date: null,
    expected_payment_date: null,
    payment_received: false,
    payment_received_date: null,
    expected_refund_date: "2026-09-20",
    refund_received: false,
    refund_received_date: null,
    product_url: "",
    publish_url: "",
    notes: "发布后 15 天返本金。",
    completed: false,
    archived_at: null,
  },
  {
    id: "demo-cos",
    user_id: null,
    created_at: "2026-08-25T08:00:00Z",
    updated_at: "2026-08-25T08:00:00Z",
    brand: "COS",
    product_name: "训练外套",
    product_category: "卫衣",
    cooperation_date: "2026-08-25",
    product_image_url: null,
    platform: "小红书",
    platforms: ["小红书"],
    product_price: 799,
    base_fee: 1200,
    commission: "",
    advance_amount: null,
    received_date: "2026-08-25",
    shoot_deadline: "2026-08-30",
    shoot_date: "2026-08-30",
    publish_deadline: "2026-08-31",
    publish_date: "2026-08-31",
    expected_payment_date: "2026-08-31",
    payment_received: false,
    payment_received_date: null,
    expected_refund_date: null,
    refund_received: false,
    refund_received_date: null,
    product_url: "",
    publish_url: "",
    notes: "发布后截图给品牌确认。",
    completed: false,
    archived_at: null,
  },
];
