import type { Deal } from "./types";

export const demoDeals: Deal[] = [
  {
    id: "demo-nike",
    user_id: null,
    created_at: "2026-08-28T08:00:00Z",
    updated_at: "2026-08-28T08:00:00Z",
    brand: "Nike",
    product_name: "黑色运动裤",
    product_image_url: null,
    platform: "小红书",
    product_price: 399,
    base_fee: 800,
    commission: "10%",
    advance_amount: 399,
    received_date: "2026-08-26",
    shoot_date: "2026-08-29",
    publish_deadline: "2026-09-03",
    publish_date: null,
    expected_payment_date: "2026-09-18",
    expected_refund_date: "2026-09-18",
    product_url: "",
    publish_url: "",
    notes: "健身房或户外场景，评论区带品牌 tag。",
  },
  {
    id: "demo-ubras",
    user_id: null,
    created_at: "2026-08-27T08:00:00Z",
    updated_at: "2026-08-27T08:00:00Z",
    brand: "Ubras",
    product_name: "白色上衣",
    product_image_url: null,
    platform: "抖音",
    product_price: null,
    base_fee: 600,
    commission: "",
    advance_amount: null,
    received_date: null,
    shoot_date: null,
    publish_deadline: "2026-09-05",
    publish_date: null,
    expected_payment_date: null,
    expected_refund_date: null,
    product_url: "",
    publish_url: "",
    notes: "",
  },
  {
    id: "demo-adidas",
    user_id: null,
    created_at: "2026-08-26T08:00:00Z",
    updated_at: "2026-08-26T08:00:00Z",
    brand: "Adidas",
    product_name: "白鞋",
    product_image_url: null,
    platform: "小红书",
    product_price: 399,
    base_fee: null,
    commission: "",
    advance_amount: 399,
    received_date: null,
    shoot_date: null,
    publish_deadline: null,
    publish_date: null,
    expected_payment_date: null,
    expected_refund_date: "2026-09-20",
    product_url: "",
    publish_url: "",
    notes: "发布后 15 天返本金。",
  },
];

